version: '3.9'

services:
  db:
    image: postgres:16
    container_name: aubergine_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: streamingdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: aubergine_pgadmin
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aubergine.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: '["local"]'
    ports:
      - 8081:80

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aubergine_app
    restart: on-failure
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/streamingdb?sslmode=disable
      STRIPE_SECRET_KEY: sk_test_mockkey
      JwtSecret: supersecretjwtkey
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
